- name: Polkadot Validator Setup
  hosts: virtsrv
  tasks:
    - name: Create VM
      tags: up
      shell: |
        qm create 9000 --memory 2048 --net0 virtio,bridge=vmbr0 \
          --name dotval0 \
          --ipconfig0 gw=192.168.128.1,ip=192.168.128.40/24 \
          --nameserver 192.168.128.1 \
          --searchdomain vnet \
          --sshkeys ./id_rsa.pub
    - name: Configure VM
      tags: up
      shell: |
        qm importdisk 9000 Arch-Linux-x86_64-cloudimg-20210619.26314.qcow2 local-lvm
        qm set 9000 --scsihw virtio-scsi-pci --scsi0 local-lvm:vm-9000-disk-0
        qm set 9000 --ide2 local-lvm:cloudinit
        qm set 9000 --boot c --bootdisk scsi0
    - name: Start VM
      tags: go
      shell: |
        qm start 9000
    - name: Destroy VM
      tags: down
      shell: |
        qm stop 9000
        qm destroy 9000 --purge
