dotval:
  hosts:
    192.168.128.40
  vars:
    ansible_user: arch
virtsrv:
  hosts:
    192.168.128.2:
    192.168.128.3:
    192.168.128.4:
  vars:
    ansible_user: root
all:
  vars:
    unprivileged_user: vince
